coverage:
  status:
    project:
      default:
        target: 97%
        threshold: 1%
    patch:
      default:
        target: 90%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "examples/"
  - "**/__pycache__"
  - "*.pyc"
